/**
 * Sistema de diseno Chifa Wok  (Material Design 3, esquema "Andean Dragon")
 *   Primario  #af101a  rojo chifa        Secundario #795900 / #fbc02d  dorado
 *   Terciario #0058a2  azul asistente    Neutro     #212121
 * Tipografia: Montserrat (titulares) + Inter (cuerpo).
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-tertiary-container": "#f0f4ff",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed-dim": "#a5c8ff",
        "secondary-container": "#fec330",
        "on-primary-container": "#fff2f0",
        "on-background": "#1b1c1c",
        "primary-fixed-dim": "#ffb3ac",
        "on-secondary-container": "#6f5100",
        "on-surface": "#1b1c1c",
        "secondary": "#795900",
        "inverse-primary": "#ffb3ac",
        "primary-container": "#d32f2f",
        "on-primary-fixed-variant": "#930010",
        "primary": "#af101a",
        "tertiary-container": "#0770cc",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffdfa0",
        "on-secondary-fixed-variant": "#5c4300",
        "outline-variant": "#e4beba",
        "secondary-fixed-dim": "#f8bd2a",
        "on-primary-fixed": "#410003",
        "background": "#fcf9f8",
        "tertiary-fixed": "#d4e3ff",
        "surface-tint": "#ba1a20",
        "tertiary": "#0058a2",
        "primary-fixed": "#ffdad6",
        "on-secondary-fixed": "#261a00",
        "outline": "#8f6f6c",
        "surface-container": "#f0eded",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-surface": "#303030",
        "on-secondary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-tertiary-fixed-variant": "#004786",
        "inverse-on-surface": "#f3f0ef",
        "surface": "#fcf9f8",
        "on-error": "#ffffff",
        "surface-dim": "#dcd9d9",
        "on-surface-variant": "#5b403d",
        "surface-container-high": "#eae7e7",
        "on-tertiary-fixed": "#001c3a",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        md: "24px", "margin-desktop": "40px", lg: "48px", xs: "4px",
        "margin-mobile": "16px", base: "8px", gutter: "24px", sm: "12px", xl: "80px",
      },
      fontFamily: {
        "display-lg": ["Montserrat", "system-ui", "sans-serif"],
        "headline-lg": ["Montserrat", "system-ui", "sans-serif"],
        "headline-md": ["Montserrat", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "label-md": ["Inter", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
